server:
  port: 8080
  servlet:
    context-path: /EGO
spring:
  datasource:
    url: jdbc:mysql://192.168.0.124:3306/ego?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.pojo
  mapper-locations: classpath:mybatis/*.xml